### ISSUE TITLE
Bug?

### ISSUE THREAD

**Issue by kay011** [ZuoFuhong/go-IM#2]
func WSHandler(w http.ResponseWriter, r *http.Request) {
	conn, e := upgrader.Upgrade(w, r, nil)
	if e != nil {
		log.Print(e)
		return
	}
	ctx := NewConnContext(conn)
	ctx.DoConn()

	messageChan := make(chan defs.MessageItem)
	pushChan = &messageChan
	service.MessageService.PushChan = pushChan
	DoSend()
}

`ctx.DoConn()`里面是 无限循环， 下面的 几行能走到吗？

**Comment by ZuoFuhong** [comment]
感谢提醒，问题已修复
